"""create 'tasks_categories' table

Revision ID: 98746fe43561
Revises: ed12485aba06
Create Date: 2021-12-02 15:54:15.874134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98746fe43561'
down_revision = 'ed12485aba06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasks', sa.Column('eisenhower_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'eisenhowers', ['eisenhower_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'eisenhower_id')
    op.drop_table('tasks_categories')
    # ### end Alembic commands ###
